// Library
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';
import { IsInt, IsString } from 'class-validator';
import { ApiModelProperty } from '@nestjs/swagger';

export interface IGroupMember {
    id: number;
    // -- AutoGenerated Model Interface --
	groupId: number;
	memberId: number;
	date: Date;
}

@Entity('groupMember')
export class GroupMemberModel implements IGroupMember {
    
    @PrimaryGeneratedColumn()
    @ApiModelProperty()
    @IsInt()
    id: number;

    // -- Autogenerated Model Definition --
	@Column('int')
	@ApiModelProperty()
	groupId: number; 

	@Column('int')
	@ApiModelProperty()
	@IsInt()
	memberId: number;

	@Column('text')
	@ApiModelProperty({ type: Date })
	@IsString()
	date: Date;

}